Adapt script with new structure

diff --git a/copier.yml b/copier.yml
--- a/copier.yml
+++ b/copier.yml
@@ -1,5 +1,10 @@
-_templates_suffix: ".j2"
 _subdirectory: template
+_templates_suffix: ".j2"
+
+_message_before_copy: |
+    The template will be generated into "{{ _copier_conf.dst_path }}".
+    It is REQUIRED that the target is a sub-directory inside your $HOME directory.
+    Otherwise, the dotfiles will not work as expected. Please abort and specify a correct target.
 
 user_name:
   type: str
@@ -25,8 +30,12 @@ backup_dir:
   when: false
 
 _tasks:
-  - name: "Initial setup: install zsh and oh-my-zsh"
+  - name: "Initial setup. Execute once after generating the template."
     command: |
-      chmod +x ./{{ dotfiles_dir }}/{{ setup_script }}.sh
-      ./{{ dotfiles_dir }}/{{ setup_script }}.sh
+      if [ "$(dirname {{ _copier_conf.dst_path }})" != "$HOME" ] && [ "{{ _copier_conf.data.simulator }}" != "true" ]; then
+          echo "ABORTED. Template must be initialized to a sub-directory inside $HOME."
+          exit 1
+      fi
+      chmod +x ./{{ setup_script }}.sh
+      ./{{ setup_script }}.sh
     when: "{{ _copier_operation == 'copy' and _copier_conf.os in ['linux', 'macos'] }}"
